language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xclip
  - sudo apt-get install -y python3-crypto
install:
  - sudo pip install pyperclip urwid

script:
  - python -m unittest discover
