language: python
python:
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xclip python3-crypto
install:
  - pip3 install pyperclip urwid

script:
  - python3 -m unittest discover
