language: python
python:
  - "3.4"

sudo: false

addons:
  apt:
    packages:
    - xclip

install:
  - pip install pyperclip urwid pycrypto>=2.6

script:
  - ./mdp.py -v
  - python -m unittest discover
